
name: Webnotes rebuild

on:
  repository_dispatch:
    types: [ build_webnotes_gh ]

jobs: 

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]
        
    env:
      CI: false
    
    steps:

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clone current repo
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Clone notes repo
        uses: actions/checkout@v2
        with: 
          repository: nerjs/webnotes
          ref: master
          path: __webnotes_master


      - name: Build client
        run : |
          cd __webnotes_master/packages/client
          yarn 
          cat .env.gh > .env
          eval "PUBLIC_URL=/webnotes/ \
            REACT_APP_API_SERVER_HOST=${{ github.event.client_payload.server_host }} \
            REACT_APP_API_SERVER_PATH=${{ github.event.client_payload.gql_path }} \
            REACT_APP_SUBSCRIBE_SERVER_PATH=${{ github.event.client_payload.subscribe_path }} \
            yarn build"



      - name: Clear dir
        run : |
          rm -rf ./webnotes/*
          mkdir -v -p ./webnotes 

      - name: Copy build
        run : cp -r __webnotes_master/packages/client/build/* ./webnotes 

      - name: Remove webnotes repo 
        run : rm -rf __webnotes_master

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: nerjs
          author_email: nerjs.stap@gmail.com
          message: "notes_bs: Rebuild from dispatch"
          ref: master
          add: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}